#!/usr/bin/env python3
"""Emit model/generated/mfcc_tables.c/h.

Replicates tensorflow/core/kernels/{spectrogram,mfcc_mel_filterbank,mfcc_dct}.cc
as used by ML-zoo KWS preprocessing:
  audio_spectrogram(window_size=640, stride=320, magnitude_squared=True)
  mfcc(sample_rate=16000, upper=4000, lower=20, filterbank_channels=40, dct_coefficient_count=10)

Tables are emitted as float hex literals so host and target use bit-identical
constants (no libm cos/log at runtime).
"""
import math
import os

SAMPLE_RATE = 16000
WIN = 640
HOP = 320
NFFT = 1024
NBINS = NFFT // 2 + 1        # 513
NMEL = 40
NDCT = 10
FLO, FHI = 20.0, 4000.0


def freq_to_mel(f):
    return 1127.0 * math.log1p(f / 700.0)


def fhex(v):
    return float(v).hex() + "f" if v != 0 else "0.0f"


def main(outdir):
    os.makedirs(outdir, exist_ok=True)
    # periodic Hann
    hann = [0.5 - 0.5 * math.cos(2 * math.pi * i / WIN) for i in range(WIN)]

    # mel filterbank (TF MfccMelFilterbank::Initialize)
    mel_low, mel_hi = freq_to_mel(FLO), freq_to_mel(FHI)
    mel_spacing = (mel_hi - mel_low) / (NMEL + 1)
    center = [mel_low + mel_spacing * (i + 1) for i in range(NMEL + 1)]
    hz_per_sbin = 0.5 * SAMPLE_RATE / (NBINS - 1)
    start_index = int(1.5 + FLO / hz_per_sbin)
    end_index = int(FHI / hz_per_sbin)
    band_mapper = [0] * NBINS
    channel = 0
    for i in range(NBINS):
        melf = freq_to_mel(i * hz_per_sbin)
        if i < start_index or i > end_index:
            band_mapper[i] = -2
        else:
            while channel < NMEL and center[channel] < melf:
                channel += 1
            band_mapper[i] = channel - 1
    weights = [0.0] * NBINS
    for i in range(NBINS):
        ch = band_mapper[i]
        if i < start_index or i > end_index:
            weights[i] = 0.0
        elif ch >= 0:
            weights[i] = (center[ch + 1] - freq_to_mel(i * hz_per_sbin)) / (center[ch + 1] - center[ch])
        else:
            weights[i] = (center[0] - freq_to_mel(i * hz_per_sbin)) / (center[0] - mel_low)

    # DCT (TF MfccDct)
    fnorm = math.sqrt(2.0 / NMEL)
    arg = math.pi / NMEL
    dct = [[fnorm * math.cos(i * arg * (j + 0.5)) for j in range(NMEL)] for i in range(NDCT)]

    h = f"""/* AUTO-GENERATED by model/gen_mfcc_tables.py -- do not edit */
#ifndef MFCC_TABLES_H
#define MFCC_TABLES_H
#include <stdint.h>
#define MFCC_SAMPLE_RATE {SAMPLE_RATE}
#define MFCC_WIN {WIN}
#define MFCC_HOP {HOP}
#define MFCC_NFFT {NFFT}
#define MFCC_NBINS {NBINS}
#define MFCC_NMEL {NMEL}
#define MFCC_NDCT {NDCT}
#define MFCC_START_INDEX {start_index}
#define MFCC_END_INDEX {end_index}
extern const float   mfcc_hann[MFCC_WIN];
extern const float   mfcc_mel_weights[MFCC_NBINS];
extern const int16_t mfcc_band_mapper[MFCC_NBINS];
extern const float   mfcc_dct[MFCC_NDCT * MFCC_NMEL];
#endif
"""

    def arr(name, ctype, vals, fmt, per=8):
        out = [f"const {ctype} {name}[{len(vals)}] SECTION_MFCC_TABLES = {{"]
        for i in range(0, len(vals), per):
            out.append("    " + ", ".join(fmt(v) for v in vals[i:i + per]) + ",")
        out.append("};")
        return "\n".join(out)

    c = "/* AUTO-GENERATED by model/gen_mfcc_tables.py -- do not edit */\n"
    c += "#include \"placement.h\"\n#include \"mfcc_tables.h\"\n\n"
    c += arr("mfcc_hann", "float", hann, fhex) + "\n\n"
    c += arr("mfcc_mel_weights", "float", weights, fhex) + "\n\n"
    c += arr("mfcc_band_mapper", "int16_t", band_mapper, str, 16) + "\n\n"
    c += arr("mfcc_dct", "float", [v for row in dct for v in row], fhex) + "\n"
    with open(os.path.join(outdir, "mfcc_tables.h"), "w") as f:
        f.write(h)
    with open(os.path.join(outdir, "mfcc_tables.c"), "w") as f:
        f.write(c)
    print(f"wrote mfcc tables: start_index={start_index} end_index={end_index}")


if __name__ == "__main__":
    main(os.path.join(os.path.dirname(__file__), "generated"))
